#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x5_3(KC_Q, KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_LBRC, LCTL_T(KC_A), LALT_T(KC_R), LSFT_T(KC_S), LGUI_T(KC_T), KC_G, KC_M, LGUI_T(KC_N), LSFT_T(KC_E), LALT_T(KC_I), LCTL_T(KC_O), KC_Z, KC_X, KC_C, KC_D, KC_V, KC_K, KC_H, KC_RBRC, KC_QUOT, KC_SCLN, LT(1,KC_ESC), KC_SPC, LT(3,KC_TAB), LT(4,KC_ENT), KC_BSPC, LT(2,KC_DEL)),
    [1] = LAYOUT_split_3x5_3(KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, LSFT(KC_7), LSFT(KC_QUOT), LALT(KC_NUBS), LALT(KC_QUOT), LALT(KC_MINS), LSFT(KC_MINS), LSFT(KC_1), KC_COMM, KC_DOT, KC_SLSH, KC_PERC, KC_HASH, LSFT(KC_6), LALT(KC_2), LSFT(KC_GRV), KC_MINS, LSFT(KC_0), LSFT(KC_COMM), LSFT(KC_DOT), LSFT(KC_MINS), KC_NO, KC_NO, KC_ENT, KC_NO, KC_NO, KC_NO)
};



#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C

